export const PET_TYPES = [
  'Dogs',
  'Cats',
  'Birds',
  'Fish',
  'Small Pets',
]

export const PRODUCT_STATUSES = ['Active', 'Draft', 'Out of Stock']

export const EMPTY_PRODUCT = {
  name: '',
  slug: '',
  sku: '',
  barcode: '',
  brand: '',
  petType: 'Dogs',
  category: '',
  subcategory: '',
  description: '',
  shortDescription: '',
  price: '',
  mrp: '',
  discount: 0,
  tax: 5,
  stock: '',
  lowStockThreshold: 10,
  images: [''],
  weight: '',
  size: '',
  flavor: '',
  ageGroup: '',
  material: '',
  ingredients: '',
  shippingWeight: '',
  dimensions: '',
  deliveryAvailable: true,
  status: 'Draft',
  featured: false,
  bestseller: false,
  newArrival: false,
  active: true,
  seoTitle: '',
  seoDescription: '',
  seoKeywords: '',
  canonicalUrl: '',
  ogTitle: '',
  ogDescription: '',
  socialImage: '',
  variants: [],
  video: '',
  benefits: '',
  usageInstructions: '',
  minOrderQty: 1,
  color: '',
}

export const EMPTY_VARIANT = {
  label: '',
  sku: '',
  price: '',
  mrp: '',
  stock: '',
}
